version: '2'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./jvm.options:/usr/share/elasticsearch/config/jvm.options
      - index_data:/usr/share/elasticsearch/data
    ports:
    - 9200:9200
    environment:
      - node.name = elasticsearch
      - http.host = 0.0.0.0
      - transport.host = localhost
      - network.host = 0.0.0.0
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g -Dlog4j2.formatMsgNolookups=true"
    ulimits:
      memlock:
        soft: -5
        hard: -5
    mem_limit: 5g
    restart: always

